# ENV
config_name: "cartpole_1.yaml"
bins_1: 25
bins_2: 25
bins_3: 25
bins_4: 25

# TRAINING
n_episodes: 20000
n_steps: 200
exploration_ratio: 1.0
learning_rate: 0.1
discount_factor: 0.99
e_decay_limit: 0.05
e_decay_rate: 0.01

# MISC
render: False
report_file: False
