# ENV
config_name: "mountaincar_1.yaml"
bins_pos: 100
bins_vel: 100

# TRAINING
n_episodes: 8000
n_steps: 200
exploration_ratio: 0.8
learning_rate: 0.9
discount_factor: 0.9
e_decay_limit: 0.05
e_decay_rate: 0.01

# MISC
render: False
report_file: False
