config_name: "mountaincar_1.yaml"
n_episodes: 10000
n_steps: 200
exploration_ratio: 0.8
learning_rate: 0.9
discount_factor: 0.9
discretization_pos: 100
discretization_vel: 100
render: False
report_file: False
