config_name: "mountaincar_1.yaml"
n_episodes: 10000
n_steps: 200
exploration_ratio: 0.8
learning_rate: 0.2
discount_factor: 0.9
discretization_pos: 5
discretization_vel: 5
render: False
report_file: False
